config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # this is the default content that is shown when you access to http://localhost:3000
  root 'pages#index'

  # Here are the roots to access login page.
  get '/login', to: 'user_sessions#new'
  # Here is the root when you login, and create session for user
  post '/sessions', to: 'user_sessions#create'
  # This is to remove session for user and log him out
  delete '/sessions', to: 'user_sessions#destroy'

  # Here is the link to the page where the user edit his password
  get '/edit_password', to: 'users#edit_password'
  # Here is the link to save the new password and go back to root the index page.
  patch '/edit_password', to: 'users#update_password'

  # Here is the link to send the user to the profile edition page
  get '/profile/:id', to: 'users#edit_profile', as: 'profile'
  # Here is the link to update the user profile and send him to index page.
  patch '/profile/:id', to: 'users#update_profile', as: 'edit_profile'

  # Here are the links to go to new user form, and to create user.
  get '/users/new', to: 'users#new'
  post '/users/new', to: 'users#create'

  # Room roots
  get '/user/:id/rooms', to: 'room#index', as: 'user_rooms'
  # Room View
  get '/user/:id/rooms/:room_id', to: 'room#view', as: 'view_user_room'

  # Show room create form
  get '/rooms/new', to: 'room#new'
  # Submit room to be created
  post '/rooms', to: 'room#create', as: 'create_room'
  # To Edit room
  patch '/rooms/:id', to: 'room#edit', as: 'edit_room'
  # Show Search room form
  get '/rooms/search', to: 'room#search', as: 'search_room'
  get '/rooms/search/:id', to: 'room#details', as: 'view_room'

  # Reservations list
  get '/user/:id/reservations', to: 'reservations#index', as: 'list_user_reservations'
  # New reservation for room
  get '/reservations/room/:room_id', to: 'reservations#new', as: 'new_reservation'
  # Create reservation
  post '/reservation/room/:room_id/create', to: 'reservations#create', as: 'create_reservation'

end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true
  validates :introduction, presence: true
  validates :address, presence: true
  validates :fee, presence: true
  validate :validate_fee

  has_one_attached :image
  belongs_to :user
  has_many :reservations

  private

  def validate_fee
    if fee && fee < 1
      errors.add(:fee, 'must be greater than 1')
    end
  end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
  def index
    if current_user
      @rooms = current_user.rooms
    else
      redirect_to root_path
    end
  end

  def view
    @room = Room.find(params[:room_id])
  end

  def new
    @room = Room.new
  end

  def create
    if current_user
      @room = Room.new(room_params)
      @room.user = current_user

      if @room.save
        flash[:notice] = "Room created successfully"
        redirect_to user_rooms_path(current_user.id)
      else
        flash[:alert] = "Room not created"
        render :new, status: :unprocessable_entity
      end
    else
      redirect_to root_path
    end
  end

  def edit
    if current_user
    else
      redirect_to root_path
    end
  end

  def search
    if current_user
      area_where_sentences = []
      free_text_where_sentences = []
      text_search = params[:text_search]
      areas = params[:areas]


      if areas
        for area in areas
          area_where_sentences << "lower(address) like '%" + area.downcase + "%'"
        end
      end

      if text_search
        for word in text_search.split(/\W+/)
          free_text_where_sentences << "lower(name) like '%" + word.downcase + "%' or lower(introduction) like '%" + word.downcase + "%'"
        end
      end

      conditions = nil
      if area_where_sentences.length() > 0 && free_text_where_sentences.length() > 0
        conditions = "(" + area_where_sentences.join(" or ") + ") and (" + free_text_where_sentences.join(" or ") + ")"
      elsif area_where_sentences.length() > 0
        conditions = area_where_sentences.join(" or ")
      elsif free_text_where_sentences.length() > 0
          conditions = free_text_where_sentences.join(" or ")
      end

      if conditions
        @rooms = Room.where(conditions)
      end

      @text_search = text_search
      @areas = areas
      @conditions = conditions

    else
      redirect_to root_path
    end
  end

  def details
    if current_user
      @room = Room.find(params[:id])
    else
      redirect_to root_path
    end
  end

  private

  def room_params
    params.require(:room).permit(:name, :introduction, :address, :fee, :image)
  end

  def search_params
    params.permit(:text_search, :areas)
  end

  def view_room_params
    params.permit(:id)
  end

end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/room/details.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <% if @room.image.attached? %>
                <%= image_tag url_for(@room.image), class: 'card-img-top', data: { turbolinks: false }, :style => "max-height:400px; object-fit: contain;" %>
            <% else %>
                <img src="/default_room.jpg" class="card-img-top" />
            <% end %>
            <div class="card-body">
                <h5 class="card-title"><%= @room.name %></h5>
                <p class="card-text"><%= @room.introduction %></p>
            </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Address: <%= @room.address %></li>
                    <li class="list-group-item">Fee: <%= @room.fee %></li>
                    <li class="list-group-item">Created at: <%= @room.created_at.strftime("%F") %></li>
                </ul>
            <div class="card-body">
                <a href="<%= search_room_path %>" class="card-link">Back to search</a>
            </div>
        </div>
    </div>
</div>

app/views/room/index.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
        <h3>User rooms</h3>
        </div>
        <div class="col-2">
            <%= link_to "New Room", rooms_new_path, class: 'btn btn-primary', data: { turbolinks: false }  %>
        </div>
    </div>
    <div class="row mt-2 row-cols-1 gy-2 justify-content-center">
        <% @rooms.each do |room| %>
            <div class="col-13 card md-6">
                <div class="row">
                    <div class="col-md-4">
                        <% if room.image.attached? %>
                            <%= image_tag url_for(room.image), class: 'img-fluid rounded-start', data: { turbolinks: false }, :style => "max-height:400px; object-fit: contain;" %>
                        <% else %>
                            <img src="/default_room.jpg" class="img-fluid rounded-start" style="max-height:400px; object-fit: contain;" />
                        <% end %>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h2 class="card-title"><%= link_to room.name, view_user_room_path(current_user.id, room.id), data: { turbolinks: false } %></h2>
                            <p class="card-text"><%= room.introduction %></p>
                            <p class="card-text"><small class="text-muted"><%= room.address %></small></p>
                            <p class="card-text"><small class="text-muted"><%= room.fee %></small></p>
                            <p class="card-text"><small class="text-muted"><%= room.created_at.strftime("%F") %></small></p>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/room/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="mb-4">Change Password</h2>
      <%= form_with model: @room, :url => create_room_path do |f| %>
        <% if @room.errors.any? %>
          <div class="mb-3">
            <ul>
              <% @room.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="mb-3">
          <%= f.label :name, class: "form-label"  %><br>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :introduction, class: "form-label"  %><br>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :address, class: "form-label"  %><br>
          <%= f.text_field :address, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :fee, class: "form-label"  %><br>
          <%= f.number_field :fee, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :image, class: "form-label"  %><br>
          <%= f.file_field :image, class: "form-control" %>
        </div>
        <%= f.submit 'Save', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/room/search.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <%= form_with url: search_room_path, method: :get do |f| %>
                <div class="form-group row">
                    <label for="text_search">Free text search</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" name="text_search" id="text_search" rows="3" value="<%= @text_search %>"><%= @text_search %></textarea>
                    </div>
                </div>
                <div class="form-group row mt-2">
                    <label class="col-form-label col-md-auto">Areas</label>
                    <div class="w-100"></div>
                    <div class="form-check col-md-auto">
                        <input class="form-check-input" type="checkbox" name="areas[]" id="areas1" value="Tokyo" <%= @areas && @areas.include?("Tokyo") ? "checked" : "" %> >
                        <label class="form-check-label" for="areas1">
                            Tokyo
                        </label>
                    </div>
                    <div class="form-check col-md-auto">
                        <input class="form-check-input" type="checkbox" name="areas[]" id="areas2" value="Osaka" <%= @areas && @areas.include?("Osaka") ? "checked" : "" %> >
                        <label class="form-check-label" for="areas2">
                            Osaka
                        </label>
                    </div>
                    <div class="form-check col-md-auto">
                        <input class="form-check-input" type="checkbox" name="areas[]" id="areas3" value="Kyoto" <%= @areas && @areas.include?("Kyoto") ? "checked" : "" %> >
                        <label class="form-check-label" for="areas3">
                            Kyoto
                        </label>
                    </div>
                    <div class="form-check col-md-auto">
                        <input class="form-check-input" type="checkbox" name="areas[]" id="areas4" value="Sapporo" <%= @areas && @areas.include?("Sapporo") ? "checked" : "" %> >
                        <label class="form-check-label" for="areas4">
                            Sapporo
                        </label>
                    </div>
                </div>
                <div class="form-group row mt-2">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
    <% if @rooms %>
        <div class="row mt-2 row-cols-1 gy-2 justify-content-center">
            <h5><strong>Search results: <%= @rooms.length() %></strong</h5>
        </div>
        <div class="row mt-2 row-cols-1 gy-2 justify-content-center">
            <% @rooms.each do |room| %>
                <div class="col-13 card md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <% if room.image.attached? %>
                                <%= image_tag url_for(room.image), class: 'img-fluid rounded-start', data: { turbolinks: false }, :style => "max-height:400px; object-fit: contain;" %>
                            <% else %>
                                <img src="/default_room.jpg" class="img-fluid rounded-start" style="max-height:400px; object-fit: contain;" />
                            <% end %>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h2 class="card-title"><%= link_to room.name, view_room_path(room.id), data: { turbolinks: false } %></h2>
                                <p class="card-text"><%= room.introduction %></p>
                                <p class="card-text"><small class="text-muted"><%= room.address %></small></p>
                                <p class="card-text"><small class="text-muted"><%= room.fee %></small></p>
                                <p class="card-text"><small class="text-muted"><%= room.created_at.strftime("%F") %></small></p>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <%= link_to 'Do Reservation', new_reservation_path(room.id), data: { turbolinks: false }, class: 'btn btn-primary' %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/room/view.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <% if @room.image.attached? %>
                <%= image_tag url_for(@room.image), class: 'card-img-top', data: { turbolinks: false }, :style => "max-height:400px; object-fit: contain;" %>
            <% else %>
                <img src="/default_room.jpg" class="card-img-top" style="max-height:400px; object-fit: contain;"/>
            <% end %>
            <div class="card-body">
                <h5 class="card-title"><%= @room.name %></h5>
                <p class="card-text"><%= @room.introduction %></p>
            </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Address: <%= @room.address %></li>
                    <li class="list-group-item">Fee: <%= @room.fee %></li>
                    <li class="list-group-item">Created at: <%= @room.created_at.strftime("%F") %></li>
                </ul>
            <div class="card-body">
                <a href="<%= user_rooms_path(current_user.id) %>" class="card-link">Back to List</a>
            </div>
        </div>
    </div>
</div>