config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # this is the default content that is shown when you access to http://localhost:3000
  root 'pages#index'

  # Here are the roots to access login page.
  get '/login', to: 'user_sessions#new'
  # Here is the root when you login, and create session for user
  post '/sessions', to: 'user_sessions#create'
  # This is to remove session for user and log him out
  delete '/sessions', to: 'user_sessions#destroy'

  # Here is the link to the page where the user edit his password
  get '/edit_password', to: 'users#edit_password'
  # Here is the link to save the new password and go back to root the index page.
  patch '/edit_password', to: 'users#update_password'

  # Here is the link to send the user to the profile edition page
  get '/profile/:id', to: 'users#edit_profile', as: 'profile'
  # Here is the link to update the user profile and send him to index page.
  patch '/profile/:id', to: 'users#update_profile', as: 'edit_profile'

  # Here are the links to go to new user form, and to create user.
  get '/users/new', to: 'users#new'
  post '/users/new', to: 'users#create'

  # Room roots
  get '/user/:id/rooms', to: 'room#index', as: 'user_rooms'
  # Room View
  get '/user/:id/rooms/:room_id', to: 'room#view', as: 'view_user_room'

  # Show room create form
  get '/rooms/new', to: 'room#new'
  # Submit room to be created
  post '/rooms', to: 'room#create', as: 'create_room'
  # To Edit room
  patch '/rooms/:id', to: 'room#edit', as: 'edit_room'
  # Show Search room form
  get '/rooms/search', to: 'room#search', as: 'search_room'
  get '/rooms/search/:id', to: 'room#details', as: 'view_room'

  # Reservations list
  get '/user/:id/reservations', to: 'reservations#index', as: 'list_user_reservations'
  # New reservation for room
  get '/reservations/room/:room_id', to: 'reservations#new', as: 'new_reservation'
  # Create reservation
  post '/reservation/room/:room_id/create', to: 'reservations#create', as: 'create_reservation'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :rooms
  has_many :reservations
  has_one_attached :image
  validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # This list all users, but is not linked to any view at this time
  def index
    @users = User.all
  end

  # Prepare new user form
  def new
    @user = User.new
  end

  # Create new user and go to index
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User created successfully"
      redirect_to root_path
    else
      flash[:alert] = "User not created"
      render :new, status: :unprocessable_entity
    end
  end

  # Prepare view for user password edit form
  def edit_password
    if current_user.blank?
      redirect root_path
    end
    @user = current_user
  end

  # Update user password
  def update_password
    if current_user.blank?
      redirect root_path
    end
    @user = current_user
    if @user.update(user_password_params)
      redirect_to root_path, notice: 'Password was successfully updated.'
    else
      flash[:alert] = "Password hasn't been updated"
      render :edit_password, status: :unprocessable_entity
    end
  end

  # Init user profile form
  def edit_profile
    if current_user.blank?
      redirect root_path
    end
    @user = current_user
  end

  # Update profile for user
  def update_profile
    require 'fileutils'
    if current_user.blank?
      redirect root_path
    end

    @user = current_user

    if @user.update(user_profile_params)
      redirect_to root_path, notice: 'Profile was successfully updated.'
    else
      flash[:alert] = "Profile hasn't been updated"
      render :edit_profile, status: :unprocessable_entity
    end
  end

  # Here methods to extract parameters that will be used in different forms
  private

  # To create new user we need this parameters
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # To change password we need this parameters
  def user_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  # To change user profile we need this parameters
  def user_profile_params
    params.require(:user).permit(:name, :introduction, :image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit_password.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="mb-4">Change Password</h2>
      <%= form_with model: @user, :url => edit_password_path do |f| %>
        <% if @user.errors.any? %>
          <div class="mb-3">
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="mb-3">
          <%= f.label :password, class: "form-label"  %><br>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, class: "form-label"  %><br>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <%= f.submit 'Create', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit_profile.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="mb-4">Change Password</h2>
      <%= form_with model: @user, :url => edit_profile_path(@user.id) do |f| %>
        <% if @user.errors.any? %>
          <div class="mb-3">
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="mb-3">
          <%= f.label :name, class: "form-label"  %><br>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :introduction, class: "form-label"  %><br>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :image, class: "form-label"  %><br>
          <%= f.file_field :image, class: "form-control" %>
        </div>
        <%= f.submit 'Save', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="mb-4">New Registration</h2>
      <%= form_with model: @user, :url => users_new_path do |f| %>
        <% if @user.errors.any? %>
          <div class="mb-3">
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="mb-3">
          <%= f.label :name, class: "form-label"  %><br>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :email, class: "form-label"  %><br>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: "form-label"  %><br>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, class: "form-label"  %><br>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <%= f.submit 'Create', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>