config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # this is the default content that is shown when you access to http://localhost:3000
  root 'pages#index'

  # Here are the roots to access login page.
  get '/login', to: 'user_sessions#new'
  # Here is the root when you login, and create session for user
  post '/sessions', to: 'user_sessions#create'
  # This is to remove session for user and log him out
  delete '/sessions', to: 'user_sessions#destroy'

  # Here is the link to the page where the user edit his password
  get '/edit_password', to: 'users#edit_password'
  # Here is the link to save the new password and go back to root the index page.
  patch '/edit_password', to: 'users#update_password'

  # Here is the link to send the user to the profile edition page
  get '/profile/:id', to: 'users#edit_profile', as: 'profile'
  # Here is the link to update the user profile and send him to index page.
  patch '/profile/:id', to: 'users#update_profile', as: 'edit_profile'

  # Here are the links to go to new user form, and to create user.
  get '/users/new', to: 'users#new'
  post '/users/new', to: 'users#create'

  # Room roots
  get '/user/:id/rooms', to: 'room#index', as: 'user_rooms'
  # Room View
  get '/user/:id/rooms/:room_id', to: 'room#view', as: 'view_user_room'

  # Show room create form
  get '/rooms/new', to: 'room#new'
  # Submit room to be created
  post '/rooms', to: 'room#create', as: 'create_room'
  # To Edit room
  patch '/rooms/:id', to: 'room#edit', as: 'edit_room'
  # Show Search room form
  get '/rooms/search', to: 'room#search', as: 'search_room'
  get '/rooms/search/:id', to: 'room#details', as: 'view_room'

  # Reservations list
  get '/user/:id/reservations', to: 'reservations#index', as: 'list_user_reservations'
  # New reservation for room
  get '/reservations/room/:room_id', to: 'reservations#new', as: 'new_reservation'
  # Create reservation
  post '/reservation/room/:room_id/create', to: 'reservations#create', as: 'create_reservation'

end

app/models/reservation.rb
class Reservation < ApplicationRecord

  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :people, presence: true
  validate :validate_fields

  belongs_to :user
  belongs_to :room

  private

  def validate_fields
    if people && people < 1
      errors.add(:people, 'must be greater than 1')
    end
    if check_in && check_in < Date.today
      errors.add(:check_in, 'Must be equal or greater than today.')
    end
    if check_in && check_out && check_in >= check_out
      errors.add(:check_out, 'Must be later than Check In.')
    end
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    if current_user
      @reservations = current_user.reservations
    else
      redirect_to root_path
    end
  end

  def new
    if current_user
      @room = Room.find(params[:room_id])
      @reservation = Reservation.new
    else
      redirect_to root_path
    end
  end

  def create
    if current_user
      @room = Room.find(params[:room_id])
      @reservation = Reservation.new(create_params)
      @reservation.user = current_user
      @reservation.room = @room

      if @reservation.save
        flash[:notice] = "Room created successfully"
        redirect_to list_user_reservations_path(current_user.id)
      else
        flash[:alert] = "Room not created"
        render :new, status: :unprocessable_entity
      end
    else
      redirect_to root_path
    end
  end

  private

  def new_params
    params.permit(:room_id)
  end

  def create_params
    params.require(:reservation).permit(:check_in, :check_out, :people)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/index.html.erb
<div class="container">
    <div class="row mt-2 row-cols-1 gy-2 justify-content-center">
        <% @reservations.each do |reservation| %>
            <div class="col-13 card md-6">
                <div class="row">
                    <div class="col-md-4">
                        <% if reservation.room.image.attached? %>
                            <%= image_tag url_for(reservation.room.image), class: 'card-img-top', data: { turbolinks: false }, :style => "max-height:400px; object-fit: contain;" %>
                        <% else %>
                            <img src="/default_room.jpg" class="img-fluid rounded-start" style="max-height:400px; object-fit: contain;" />
                        <% end %>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h2 class="card-title">Facility Name: <%= reservation.room.name %></h2>
                            <p class="card-text">Introduction: <%= reservation.room.introduction %></p>
                            <p class="card-text">Total Fee: <%= (reservation.check_out - reservation.check_in).to_i * reservation.people * reservation.room.fee %></small></p>
                            <p class="card-text">Check-in: <small class="text-muted"><%= reservation.check_in.strftime("%F") %></small></p>
                            <p class="card-text">Check-out: <small class="text-muted"><%= reservation.check_out.strftime("%F") %></small></p>
                            <p class="card-text">Confirmation Date: <small class="text-muted"><%= reservation.created_at.strftime("%F %T") %></small></p>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/reservations/new.html.erb
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h3>Reservation</h3>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <% if @room.image.attached? %>
                    <%= image_tag url_for(@room.image), class: 'card-img-top', data: { turbolinks: false }, :style => "max-height:400px; object-fit: contain;" %>
                <% else %>
                    <img src="/default_room.jpg" class="card-img-top" style="max-width: 100px; max-height: 100px; object-fit: contain;"/>
                <% end %>
                <div class="card-body">
                    <h5 class="card-title"><%= @room.name %></h5>
                    <p class="card-text"><%= @room.introduction %></p>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center mt-2">
        <div class="col-md-8">
            <h2 class="mb-4">Change Password</h2>
            <%= form_with model: @reservation, :url => create_reservation_path(@room.id) do |f| %>
                <% if @reservation.errors.any? %>
                    <div class="mb-3">
                        <ul>
                        <% @reservation.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                        </ul>
                    </div>
                <% end %>
                <div class="col-md-6">
                    <label for="checkin" class="form-label">Check In</label>
                    <%= f.date_field :check_in, class: "form-control", id: "checkin"  %>
                </div>
                <div class="col-md-6">
                    <label for="checkout" class="form-label">Check Out</label>
                    <%= f.date_field :check_out, class: "form-control", id: "checkout"  %>
                </div>
                <div class="col-md-6">
                    <label for="people" class="form-label">People</label>
                    <%= f.number_field :people, class: "form-control", id: "people"  %>
                </div>
                <div class="col-md-6">
                    <%= f.submit 'Save', class: "btn btn-primary" %>
                </div>
                <input type="hidden" id="roomId" name="room_id" value="<%= @room.id %>" />
            <% end %>
        </div>
    </div>
</div>