config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # this is the default content that is shown when you access to http://localhost:3000
  root 'pages#index'

  # Here are the roots to access login page.
  get '/login', to: 'user_sessions#new'
  # Here is the root when you login, and create session for user
  post '/sessions', to: 'user_sessions#create'
  # This is to remove session for user and log him out
  delete '/sessions', to: 'user_sessions#destroy'

  # Here is the link to the page where the user edit his password
  get '/edit_password', to: 'users#edit_password'
  # Here is the link to save the new password and go back to root the index page.
  patch '/edit_password', to: 'users#update_password'

  # Here is the link to send the user to the profile edition page
  get '/profile/:id', to: 'users#edit_profile', as: 'profile'
  # Here is the link to update the user profile and send him to index page.
  patch '/profile/:id', to: 'users#update_profile', as: 'edit_profile'

  # Here are the links to go to new user form, and to create user.
  get '/users/new', to: 'users#new'
  post '/users/new', to: 'users#create'

  # Room roots
  get '/user/:id/rooms', to: 'room#index', as: 'user_rooms'
  # Room View
  get '/user/:id/rooms/:room_id', to: 'room#view', as: 'view_user_room'

  # Show room create form
  get '/rooms/new', to: 'room#new'
  # Submit room to be created
  post '/rooms', to: 'room#create', as: 'create_room'
  # To Edit room
  patch '/rooms/:id', to: 'room#edit', as: 'edit_room'
  # Show Search room form
  get '/rooms/search', to: 'room#search', as: 'search_room'
  get '/rooms/search/:id', to: 'room#details', as: 'view_room'

  # Reservations list
  get '/user/:id/reservations', to: 'reservations#index', as: 'list_user_reservations'
  # New reservation for room
  get '/reservations/room/:room_id', to: 'reservations#new', as: 'new_reservation'
  # Create reservation
  post '/reservation/room/:room_id/create', to: 'reservations#create', as: 'create_reservation'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
          <% if current_user %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  <% if current_user.image.attached? %>
                    <%= image_tag url_for(current_user.image), style: 'width:30px', data: { turbolinks: false } %> <%= current_user.name %>
                  <% else %>
                    <img src="/default_profile.jpg" width="30" /> <%= current_user.name %>
                  <% end %>
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><%= link_to 'Change Profile', profile_path(current_user.id), class: "dropdown-item", data: { turbolinks: false } %></li>
                <li><%= link_to 'Change Password', edit_password_path, class: "dropdown-item", data: { turbolinks: false } %></li>
                <li><%= link_to 'Log Out', sessions_path, method: :delete, class: "dropdown-item", data: { turbolinks: false } %></li>
              </div>
            </div>
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <%= link_to 'My Rooms', user_rooms_path(current_user.id), class: "nav-link", data: { turbolinks: false } %>
              </li>
              <li class="nav-item">
                <%= link_to 'Room Search', search_room_path, class: "nav-link", data: { turbolinks: false } %>
              </li>
              <li class="nav-item">
                <%= link_to 'My Reservations', list_user_reservations_path(current_user.id), class: "nav-link", data: { turbolinks: false }  %>
              </li>
            </ul>
          <% else %>
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <%= link_to 'Login', login_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to 'New Registration', users_new_path, class: "nav-link" %>
              </li>
            </ul>
          <% end %>
        </div>
      </nav>
    </header>
    <% if flash.any? %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <% flash.each do |type, msg| %>
            <strong><%= msg %></strong>
        <% end %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>